experiment_name: "RQ1_Context_Ablation"
dataset_name: "your-hf-org/your-dataset"
dataset_split: "test"
models:
  - "microsoft/phi-4" # GPT-4 excluded for cost efficiency
include_message: false # Key difference from RQ0
output_dir: "../results/rq1"
temperature: 0
max_tokens: 16384
