experiment_name: "RQ3_Latency_vs_Context_Length"
dataset_name: "your-hf-org/your-dataset"
dataset_split: "test"
models:
  - "microsoft/phi-4"
include_message: true
context_lengths: [256, 512, 1024, 2048, 4096]
output_dir: "../results/rq3"
temperature: 0
max_tokens: 16384
