experiment_name: "RQ0_Performance_Gap"
dataset_name: "Berom0227/Untangling-Multi-Concern-Commits-with-Small-Language-Models"
dataset_split: "test"
models:
  llm:
    - "gpt-4-turbo"
output_dir: "../results/rq0"
temperature: 0
max_tokens: 16384
